// Code generated by entc, DO NOT EDIT.

package employee

const (
	// Label holds the string label denoting the employee type in the database.
	Label = "employee"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEMPLOYEENAME holds the string denoting the employeename field in the database.
	FieldEMPLOYEENAME = "employeename"
	// FieldEMPLOYEEPASSWORD holds the string denoting the employeepassword field in the database.
	FieldEMPLOYEEPASSWORD = "employeepassword"

	// EdgeCheckout2 holds the string denoting the checkout2 edge name in mutations.
	EdgeCheckout2 = "checkout2"

	// Table holds the table name of the employee in the database.
	Table = "employees"
	// Checkout2Table is the table the holds the checkout2 relation/edge.
	Checkout2Table = "checkouts"
	// Checkout2InverseTable is the table name for the Checkout entity.
	// It exists in this package in order to avoid circular dependency with the "checkout" package.
	Checkout2InverseTable = "checkouts"
	// Checkout2Column is the table column denoting the checkout2 relation/edge.
	Checkout2Column = "employee_checkout2"
)

// Columns holds all SQL columns for employee fields.
var Columns = []string{
	FieldID,
	FieldEMPLOYEENAME,
	FieldEMPLOYEEPASSWORD,
}
