/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntCheckout,
    EntCheckoutFromJSON,
    EntCheckoutFromJSONTyped,
    EntCheckoutToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntCustomerEdges
 */
export interface EntCustomerEdges {
    /**
     * Checkout1 holds the value of the checkout1 edge.
     * @type {Array<EntCheckout>}
     * @memberof EntCustomerEdges
     */
    checkout1?: Array<EntCheckout>;
}

export function EntCustomerEdgesFromJSON(json: any): EntCustomerEdges {
    return EntCustomerEdgesFromJSONTyped(json, false);
}

export function EntCustomerEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntCustomerEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'checkout1': !exists(json, 'checkout1') ? undefined : ((json['checkout1'] as Array<any>).map(EntCheckoutFromJSON)),
    };
}

export function EntCustomerEdgesToJSON(value?: EntCustomerEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'checkout1': value.checkout1 === undefined ? undefined : ((value.checkout1 as Array<any>).map(EntCheckoutToJSON)),
    };
}


