/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntCheckout,
    EntCheckoutFromJSON,
    EntCheckoutFromJSONTyped,
    EntCheckoutToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntEmployeeEdges
 */
export interface EntEmployeeEdges {
    /**
     * Checkout2 holds the value of the checkout2 edge.
     * @type {Array<EntCheckout>}
     * @memberof EntEmployeeEdges
     */
    checkout2?: Array<EntCheckout>;
}

export function EntEmployeeEdgesFromJSON(json: any): EntEmployeeEdges {
    return EntEmployeeEdgesFromJSONTyped(json, false);
}

export function EntEmployeeEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntEmployeeEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'checkout2': !exists(json, 'checkout2') ? undefined : ((json['checkout2'] as Array<any>).map(EntCheckoutFromJSON)),
    };
}

export function EntEmployeeEdgesToJSON(value?: EntEmployeeEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'checkout2': value.checkout2 === undefined ? undefined : ((value.checkout2 as Array<any>).map(EntCheckoutToJSON)),
    };
}


