// Code generated by entc, DO NOT EDIT.

package room

const (
	// Label holds the string label denoting the room type in the database.
	Label = "room"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldROOMNUMBER holds the string denoting the roomnumber field in the database.
	FieldROOMNUMBER = "roomnumber"

	// EdgeCheckout3 holds the string denoting the checkout3 edge name in mutations.
	EdgeCheckout3 = "checkout3"

	// Table holds the table name of the room in the database.
	Table = "rooms"
	// Checkout3Table is the table the holds the checkout3 relation/edge.
	Checkout3Table = "checkouts"
	// Checkout3InverseTable is the table name for the Checkout entity.
	// It exists in this package in order to avoid circular dependency with the "checkout" package.
	Checkout3InverseTable = "checkouts"
	// Checkout3Column is the table column denoting the checkout3 relation/edge.
	Checkout3Column = "room_checkout3"
)

// Columns holds all SQL columns for room fields.
var Columns = []string{
	FieldID,
	FieldROOMNUMBER,
}
